#!/usr/bin/env bash
set -euo pipefail

credential="${ERRANDOS_CREDENTIAL_FILE:-/root/.hermes/profiles/errandos/secrets/errandos-runtime.cred}"
runtime="$(mktemp /dev/shm/errandos-screen-runtime.XXXXXX)"
output=""

cleanup() {
  rm -f "$runtime"
  if [[ -n "$output" && -f "$output" && ! -s "$output" ]]; then rm -f "$output"; fi
}
trap cleanup EXIT

chmod 600 "$runtime"
systemd-creds decrypt --name=errandos-runtime "$credential" "$runtime" >/dev/null
set -a
# This file is host-encrypted and generated by the ErrandOS setup.
# shellcheck disable=SC1090
. "$runtime"
set +a
rm -f "$runtime"

: "${ERRANDOS_ANDROID_WORKER_SSH_HOST:?missing worker host}"
: "${ERRANDOS_ANDROID_WORKER_IDENTITY_FILE:?missing worker identity}"
: "${ERRANDOS_ANDROID_WORKER_KNOWN_HOSTS_FILE:?missing worker known-hosts file}"

cache_root="${HERMES_HOME:-/root/.hermes}/cache/errandos-screens"
install -d -m 0700 "$cache_root"
find "$cache_root" -type f -name 'blinkit-*.png' -mmin +30 -delete
output="$(mktemp "$cache_root/blinkit-XXXXXX.png")"
chmod 0600 "$output"

if ! ssh \
  -T \
  -o BatchMode=yes \
  -o IdentitiesOnly=yes \
  -o StrictHostKeyChecking=yes \
  -o "UserKnownHostsFile=$ERRANDOS_ANDROID_WORKER_KNOWN_HOSTS_FILE" \
  -i "$ERRANDOS_ANDROID_WORKER_IDENTITY_FILE" \
  "errandos-screen-agent@$ERRANDOS_ANDROID_WORKER_SSH_HOST" >"$output"; then
  rm -f "$output"
  output=""
  printf 'Blinkit screen preview is unavailable or blocked on this sensitive screen.\n'
  exit 1
fi

signature="$(od -An -tx1 -N8 "$output" | tr -d ' \n')"
if [[ "$signature" != '89504e470d0a1a0a' ]]; then
  rm -f "$output"
  output=""
  printf 'Blinkit screen preview failed validation.\n'
  exit 1
fi

printf 'Current owner-only Blinkit screen preview:\n%s\n' "$output"
