#!/usr/bin/env bash
set -euo pipefail

credential="${ERRANDOS_CREDENTIAL_FILE:-/root/.hermes/profiles/errandos/secrets/errandos-runtime.cred}"
tmp="$(mktemp /dev/shm/errandos-runtime.XXXXXX)"
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT
chmod 600 "$tmp"
systemd-creds decrypt --name=errandos-runtime "$credential" "$tmp" >/dev/null
set -a
# This file is host-encrypted and generated by the JaldiAI setup; it is not user-controlled.
# shellcheck disable=SC1090
. "$tmp"
set +a
cleanup
trap - EXIT

# This host-local MCP deployment intentionally uses the encrypted filesystem
# adapter. Production service deployments must select PostgreSQL instead.
export ERRANDOS_PERSISTENCE_MODE="${ERRANDOS_PERSISTENCE_MODE:-filesystem}"

release_entry="/opt/errandos/control-plane/current/dist/src/mcp-entry.js"
if [[ -f "$release_entry" ]]; then
  exec node "$release_entry"
fi

exec pnpm --dir /root/product-build-repos/errandos --filter @errandos/control-plane exec tsx src/mcp-entry.ts
