import { fileURLToPath } from 'node:url';
import { dirname,resolve } from 'node:path';
import { beforeAll,afterAll,beforeEach,describe,expect,it } from 'vitest';
import { PostgresApprovalRepository,PostgresAuditRepository,PostgresDatabase,PostgresLifecycleRepository,PostgresOutboxRepository,PostgresProposalRepository,PostgresTransactionRepository } from '../src/index.js';
const url=process.env['TEST_DATABASE_URL']??'postgresql:///errandos_test?host=/var/run/postgresql';
const db=new PostgresDatabase(url);
const migration=resolve(dirname(fileURLToPath(import.meta.url)),'../migrations/003_transaction_authorization.sql');
const migrationDown=resolve(dirname(fileURLToPath(import.meta.url)),'../migrations/003_transaction_authorization.down.sql');
const hash='a'.repeat(64);
async function reset():Promise<void>{await db.pool.query('DROP SCHEMA public CASCADE; CREATE SCHEMA public');await db.migrate(migration);}
async function seed(principal='owner',jti='jti'):Promise<void>{
 await db.pool.query(`INSERT INTO proposal_revisions VALUES('proposal',1,$1,'idem-'||$1,$2,'{}')`,[principal,hash]);
 await db.pool.query(`INSERT INTO approval_requests(id,principal_id,proposal_id,proposal_revision,proposal_hash,status,request_token_hash,expires_at) VALUES('approval',$1,'proposal',1,$2,'approved','token-'||$1,now()+interval '1 hour')`,[principal,hash]);
 await db.pool.query(`INSERT INTO authorization_capabilities(jti,approval_request_id,principal_id,proposal_id,proposal_revision,proposal_hash,action,issued_at,expires_at) VALUES($1,'approval',$2,'proposal',1,$3,'commit',now(),now()+interval '1 hour')`,[jti,principal,hash]);
}
async function seedApproval(status:'pending'|'approved'|'rejected'|'expired',requestExpiry="now()+interval '1 hour'",decision:'approved'|'rejected'|undefined=status==='approved'?'approved':undefined):Promise<PostgresApprovalRepository>{
 await db.pool.query(`INSERT INTO proposal_revisions VALUES('proposal',1,'owner','idem-owner',$1,'{}')`,[hash]);
 await db.pool.query(`INSERT INTO approval_requests(id,principal_id,proposal_id,proposal_revision,proposal_hash,status,request_token_hash,expires_at) VALUES('approval','owner','proposal',1,$1,$2,'token',${requestExpiry})`,[hash,status]);
 if(decision)await db.pool.query(`INSERT INTO approval_decisions(id,approval_request_id,principal_id,proposal_id,proposal_revision,proposal_hash,decision) VALUES('decision','approval','owner','proposal',1,$1,$2)`,[hash,decision]);
 return new PostgresApprovalRepository(db.pool);
}
const capability=(issuedAt=new Date(Date.now()-1_000),expiresAt=new Date(Date.now()+30_000)):{jti:string;approvalRequestId:string;principalId:string;proposalId:string;proposalRevision:number;proposalHash:string;action:string;issuedAt:Date;expiresAt:Date}=>({jti:'focused-jti',approvalRequestId:'approval',principalId:'owner',proposalId:'proposal',proposalRevision:1,proposalHash:hash,action:'commit',issuedAt,expiresAt});
const dispatch=(jti='focused-jti'):Promise<boolean>=>new PostgresTransactionRepository(db).reserveAuthorizedDispatch({attemptId:'focused-attempt',outboxId:'focused-out',principalId:'owner',proposalId:'proposal',proposalRevision:1,proposalHash:hash,capabilityJti:jti,action:'commit',outboxPayload:{}});
describe('PostgreSQL transaction durability',()=>{
 beforeAll(async()=>{expect(await db.ready()).toBe(true);});afterAll(async()=>db.close());beforeEach(reset);
 it('migrates down and reapplies cleanly',async()=>{await db.migrate(migrationDown);expect((await db.pool.query("SELECT to_regclass('audit_events') name")).rows[0].name).toBeNull();await db.migrate(migration);expect((await db.pool.query("SELECT to_regclass('audit_events') name")).rows[0].name).toBe('audit_events');});
 it('enforces exact approval binding, uniqueness, and append-only records',async()=>{await seed();await expect(db.pool.query(`UPDATE proposal_revisions SET proposal_hash=$1`,['b'.repeat(64)])).rejects.toThrow(/append-only/);await expect(db.pool.query(`DELETE FROM proposal_revisions`)).rejects.toThrow(/append-only/);await db.pool.query(`INSERT INTO proposal_revisions VALUES('proposal',2,'owner','idem-2',$1,'{}')`,['b'.repeat(64)]);expect((await db.pool.query(`SELECT revision FROM proposal_revisions WHERE proposal_id='proposal' ORDER BY revision`)).rows.map(x=>x.revision)).toEqual([1,2]);await db.pool.query(`INSERT INTO audit_events VALUES('audit','owner','created','proposal','proposal','{}')`);await expect(db.pool.query(`UPDATE audit_events SET action='changed'`)).rejects.toThrow(/append-only/);await expect(db.pool.query(`DELETE FROM audit_events`)).rejects.toThrow(/append-only/);await expect(db.pool.query(`INSERT INTO approval_requests(id,principal_id,proposal_id,proposal_revision,proposal_hash,status,request_token_hash,expires_at) VALUES('bad','other','proposal',1,$1,'pending','x',now())`,[hash])).rejects.toThrow();});
 it('isolates owners',async()=>{await seed();const proposals=new PostgresProposalRepository(db.pool);expect(await proposals.get('other','proposal',1)).toBeUndefined();expect(await proposals.get('owner','proposal',1)).toBeDefined();const approvals=new PostgresApprovalRepository(db.pool);expect(await approvals.isConsumed('other','jti')).toBeUndefined();});
 it('rejects future-issued capabilities at insertion and consumption',async()=>{const approvals=await seedApproval('approved');await expect(approvals.addCapability(capability(new Date(Date.now()+60_000),new Date(Date.now()+120_000)))).rejects.toThrow(/approved, unexpired/);await db.pool.query(`INSERT INTO authorization_capabilities(jti,approval_request_id,principal_id,proposal_id,proposal_revision,proposal_hash,action,issued_at,expires_at) VALUES('future-direct','approval','owner','proposal',1,$1,'commit',now()+interval '1 hour',now()+interval '2 hours')`,[hash]);expect(await dispatch('future-direct')).toBe(false);});
 it.each([['pending',undefined],['rejected','rejected'],['expired',undefined]] as const)('rejects %s approval for capability issuance',async(status,decision)=>{const approvals=await seedApproval(status,status==='expired'?"now()-interval '1 second'":"now()+interval '1 hour'",decision);await expect(approvals.addCapability(capability())).rejects.toThrow(/approved, unexpired/);});
 it('rejects capability expiry beyond its approval request',async()=>{const approvals=await seedApproval('approved');await expect(approvals.addCapability(capability(undefined,new Date(Date.now()+7_200_000)))).rejects.toThrow(/approved, unexpired/);});
 it('inserts and consumes a valid approved capability',async()=>{const approvals=await seedApproval('approved');await approvals.addCapability(capability());expect(await dispatch()).toBe(true);expect(await approvals.isConsumed('owner','focused-jti')).toBe(true);});
 it('rolls back consumption and reservation/outbox atomically',async()=>{await seed();const tx=new PostgresTransactionRepository(db);await expect(tx.reserveAuthorizedDispatch({attemptId:'attempt',outboxId:'out',principalId:'owner',proposalId:'proposal',proposalRevision:1,proposalHash:hash,capabilityJti:'jti',action:'commit',outboxPayload:{}},()=>{throw new Error('fault');})).rejects.toThrow('fault');expect(await new PostgresApprovalRepository(db.pool).isConsumed('owner','jti')).toBe(false);expect((await db.pool.query('SELECT count(*) n FROM commit_attempts')).rows[0].n).toBe('0');expect((await db.pool.query('SELECT count(*) n FROM transaction_outbox')).rows[0].n).toBe('0');});
 it('allows exactly one of twenty concurrent reservations',async()=>{await seed();const tx=new PostgresTransactionRepository(db);const results=await Promise.all(Array.from({length:20},(_,i)=>tx.reserveAuthorizedDispatch({attemptId:`attempt-${i}`,outboxId:`out-${i}`,principalId:'owner',proposalId:'proposal',proposalRevision:1,proposalHash:hash,capabilityJti:'jti',action:'commit',outboxPayload:{i}})));expect(results.filter(Boolean)).toHaveLength(1);expect((await db.pool.query('SELECT count(*) n FROM commit_attempts')).rows[0].n).toBe('1');expect((await db.pool.query('SELECT count(*) n FROM transaction_outbox')).rows[0].n).toBe('1');});
 it('makes leased duplicate delivery idempotent',async()=>{await seed();const tx=new PostgresTransactionRepository(db);await tx.reserveAuthorizedDispatch({attemptId:'attempt',outboxId:'out',principalId:'owner',proposalId:'proposal',proposalRevision:1,proposalHash:hash,capabilityJti:'jti',action:'commit',outboxPayload:{}});const outbox=new PostgresOutboxRepository(db.pool);await outbox.claimPending('owner','worker');expect(await outbox.markDelivered('owner','out','worker')).toBe(true);expect(await outbox.markDelivered('owner','out','worker')).toBe(true);expect((await outbox.get('owner','out'))?.deliveryCount).toBe(1);expect(await outbox.get('other','out')).toBeUndefined();});
 it('principal-scopes approvals, attempts, receipts, reconciliation, lifecycle, audit and outbox',async()=>{await seed();const approvals=new PostgresApprovalRepository(db.pool);expect(await approvals.getRequest('other','approval')).toBeUndefined();expect(await approvals.getRequest('owner','approval')).toBeDefined();const tx=new PostgresTransactionRepository(db);await tx.reserveAuthorizedDispatch({attemptId:'attempt',outboxId:'out',principalId:'owner',proposalId:'proposal',proposalRevision:1,proposalHash:hash,capabilityJti:'jti',action:'commit',outboxPayload:{}});expect(await tx.getAttempt('other','attempt')).toBeUndefined();expect(await tx.transitionAttempt('other','attempt','reserved','dispatching')).toBe(false);await tx.addReceipt({id:'receipt',commitAttemptId:'attempt',principalId:'owner',status:'ok',receipt:{}});expect(await tx.getReceipt('other','attempt')).toBeUndefined();await tx.createReconciliation({id:'recon',commitAttemptId:'attempt',principalId:'owner',status:'pending'});expect(await tx.getReconciliation('other','recon')).toBeUndefined();expect(await tx.completeReconciliation('other','recon','done',{})).toBe(false);await db.pool.query(`INSERT INTO lifecycle_events VALUES('event','attempt','owner',0,'progress','dispatch',false,true,'{}',now())`);expect(await new PostgresLifecycleRepository(db.pool).list('other','attempt')).toEqual([]);await new PostgresAuditRepository(db.pool).append({id:'audit',principalId:'owner',action:'x',subjectType:'attempt',subjectId:'attempt',metadata:{}});expect(await new PostgresAuditRepository(db.pool).list('other')).toEqual([]);const outbox=new PostgresOutboxRepository(db.pool);expect(await outbox.claimPending('other','worker')).toEqual([]);expect(await outbox.claimPending('owner','worker')).toHaveLength(1);expect(await outbox.release('other','out','worker')).toBe(false);});
});
