import type { Database } from './postgres.js';
export interface ApprovalRequestRecord { id:string; principalId:string; proposalId:string; proposalRevision:number; proposalHash:string; status:'pending'|'approved'|'rejected'|'expired'; requestTokenHash:string; expiresAt:Date }
export interface ApprovalDecisionRecord { id:string; approvalRequestId:string; principalId:string; proposalId:string; proposalRevision:number; proposalHash:string; decision:'approved'|'rejected'; decidedAt?:Date }
export interface AuthorizationCapabilityRecord { jti:string; approvalRequestId:string; principalId:string; proposalId:string; proposalRevision:number; proposalHash:string; action:string; issuedAt:Date; expiresAt:Date }
const request=(x:Record<string,unknown>):ApprovalRequestRecord=>({id:x['id'] as string,principalId:x['principal_id'] as string,proposalId:x['proposal_id'] as string,proposalRevision:x['proposal_revision'] as number,proposalHash:x['proposal_hash'] as string,status:x['status'] as ApprovalRequestRecord['status'],requestTokenHash:x['request_token_hash'] as string,expiresAt:x['expires_at'] as Date});
export class PostgresApprovalRepository {
 constructor(private readonly db:Database) {}
 async createRequest(v:ApprovalRequestRecord):Promise<void>{await this.db.query(`INSERT INTO approval_requests(id,principal_id,proposal_id,proposal_revision,proposal_hash,status,request_token_hash,expires_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[v.id,v.principalId,v.proposalId,v.proposalRevision,v.proposalHash,v.status,v.requestTokenHash,v.expiresAt]);}
 async getRequest(principalId:string,id:string):Promise<ApprovalRequestRecord|undefined>{const r=await this.db.query('SELECT * FROM approval_requests WHERE principal_id=$1 AND id=$2',[principalId,id]);return r.rows[0]?request(r.rows[0] as Record<string,unknown>):undefined;}
 async addDecision(v:ApprovalDecisionRecord):Promise<boolean>{const r=await this.db.query(`WITH changed AS (UPDATE approval_requests SET status=$3 WHERE id=$1 AND principal_id=$2 AND status='pending' AND expires_at>now() RETURNING id,principal_id,proposal_id,proposal_revision,proposal_hash) INSERT INTO approval_decisions(id,approval_request_id,principal_id,proposal_id,proposal_revision,proposal_hash,decision,decided_at) SELECT $4,id,principal_id,proposal_id,proposal_revision,proposal_hash,$3,COALESCE($5,now()) FROM changed RETURNING id`,[v.approvalRequestId,v.principalId,v.decision,v.id,v.decidedAt]);return r.rowCount===1;}
 async getDecision(principalId:string,requestId:string):Promise<ApprovalDecisionRecord|undefined>{const r=await this.db.query('SELECT * FROM approval_decisions WHERE principal_id=$1 AND approval_request_id=$2',[principalId,requestId]);const x=r.rows[0] as Record<string,unknown>|undefined;return x?{id:x['id'] as string,approvalRequestId:x['approval_request_id'] as string,principalId:x['principal_id'] as string,proposalId:x['proposal_id'] as string,proposalRevision:x['proposal_revision'] as number,proposalHash:x['proposal_hash'] as string,decision:x['decision'] as ApprovalDecisionRecord['decision'],decidedAt:x['decided_at'] as Date}:undefined;}
 async expireRequest(principalId:string,id:string):Promise<boolean>{const r=await this.db.query(`UPDATE approval_requests SET status='expired' WHERE principal_id=$1 AND id=$2 AND status='pending' RETURNING id`,[principalId,id]);return r.rowCount===1;}
 async addCapability(v:AuthorizationCapabilityRecord):Promise<void>{
  const r=await this.db.query(`INSERT INTO authorization_capabilities(jti,approval_request_id,principal_id,proposal_id,proposal_revision,proposal_hash,action,issued_at,expires_at)
   SELECT $1,r.id,r.principal_id,r.proposal_id,r.proposal_revision,r.proposal_hash,$7,$8,$9 FROM approval_requests r
   JOIN approval_decisions d ON d.approval_request_id=r.id AND d.principal_id=r.principal_id
   WHERE r.id=$2 AND r.principal_id=$3 AND r.proposal_id=$4 AND r.proposal_revision=$5 AND r.proposal_hash=$6
   AND r.status='approved' AND r.expires_at>now() AND d.decision='approved' AND $7='commit' AND $8<=now() AND $9<=r.expires_at RETURNING jti`,[v.jti,v.approvalRequestId,v.principalId,v.proposalId,v.proposalRevision,v.proposalHash,v.action,v.issuedAt,v.expiresAt]);
  if(r.rowCount!==1)throw new Error('capability requires an approved, unexpired commit request and decision');
 }
 async isConsumed(principalId:string,jti:string):Promise<boolean|undefined>{const r=await this.db.query('SELECT consumed_at IS NOT NULL consumed FROM authorization_capabilities WHERE principal_id=$1 AND jti=$2',[principalId,jti]);return (r.rows[0] as {consumed:boolean}|undefined)?.consumed;}
}
