import type { PostgresDatabase } from './postgres.js';
export type CommitStatus='reserved'|'dispatching'|'committed'|'ambiguous'|'failed_terminal'|'cancelled';
export interface ReserveDispatchInput { attemptId:string; outboxId:string; principalId:string; proposalId:string; proposalRevision:number; proposalHash:string; capabilityJti:string; action:string; outboxPayload:unknown }
export interface CommitAttemptRecord {id:string;principalId:string;proposalId:string;proposalRevision:number;proposalHash:string;capabilityJti:string;status:CommitStatus;reservedAt:Date;updatedAt:Date}
export interface TransactionReceiptRecord {id:string;commitAttemptId:string;principalId:string;providerReference?:string|undefined;status:string;receipt:unknown;createdAt?:Date|undefined}
export interface ReconciliationAttemptRecord {id:string;commitAttemptId:string;principalId:string;status:string;result?:unknown;createdAt?:Date|undefined;completedAt?:Date|undefined}
export class PostgresTransactionRepository {
 constructor(private readonly db:PostgresDatabase) {}
 async reserveAuthorizedDispatch(input:ReserveDispatchInput,afterConsume?:()=>never):Promise<boolean>{return this.db.transaction(async client=>{const capability=await client.query(`SELECT 1 FROM authorization_capabilities WHERE jti=$1 AND principal_id=$2 AND proposal_id=$3 AND proposal_revision=$4 AND proposal_hash=$5 AND action=$6 AND consumed_at IS NULL AND issued_at<=now() AND expires_at>now() FOR UPDATE`,[input.capabilityJti,input.principalId,input.proposalId,input.proposalRevision,input.proposalHash,input.action]);if(capability.rowCount!==1)return false;const reserved=await client.query(`INSERT INTO commit_attempts(id,principal_id,proposal_id,proposal_revision,proposal_hash,capability_jti,status) VALUES($1,$2,$3,$4,$5,$6,'reserved') ON CONFLICT DO NOTHING RETURNING id`,[input.attemptId,input.principalId,input.proposalId,input.proposalRevision,input.proposalHash,input.capabilityJti]);if(reserved.rowCount!==1)return false;await client.query('UPDATE authorization_capabilities SET consumed_at=now() WHERE principal_id=$1 AND jti=$2',[input.principalId,input.capabilityJti]);if(afterConsume)afterConsume();await client.query(`INSERT INTO transaction_outbox(id,principal_id,aggregate_type,aggregate_id,event_type,payload) VALUES($1,$2,'commit_attempt',$3,'dispatch_reserved',$4)`,[input.outboxId,input.principalId,input.attemptId,input.outboxPayload]);return true;});}
 async getAttempt(principalId:string,id:string):Promise<CommitAttemptRecord|undefined>{const r=await this.db.pool.query('SELECT * FROM commit_attempts WHERE principal_id=$1 AND id=$2',[principalId,id]);const x=r.rows[0] as Record<string,unknown>|undefined;return x?{id:x['id'] as string,principalId:x['principal_id'] as string,proposalId:x['proposal_id'] as string,proposalRevision:x['proposal_revision'] as number,proposalHash:x['proposal_hash'] as string,capabilityJti:x['capability_jti'] as string,status:x['status'] as CommitStatus,reservedAt:x['reserved_at'] as Date,updatedAt:x['updated_at'] as Date}:undefined;}
 async transitionAttempt(principalId:string,id:string,from:CommitStatus|CommitStatus[],to:CommitStatus):Promise<boolean>{const allowed=Array.isArray(from)?from:[from];const r=await this.db.pool.query('UPDATE commit_attempts SET status=$3,updated_at=now() WHERE principal_id=$1 AND id=$2 AND status=ANY($4::text[]) RETURNING id',[principalId,id,to,allowed]);return r.rowCount===1;}
 async addReceipt(v:TransactionReceiptRecord):Promise<void>{await this.db.pool.query('INSERT INTO transaction_receipts(id,commit_attempt_id,principal_id,provider_reference,status,receipt) VALUES($1,$2,$3,$4,$5,$6)',[v.id,v.commitAttemptId,v.principalId,v.providerReference,v.status,v.receipt]);}
 async getReceipt(principalId:string,attemptId:string):Promise<TransactionReceiptRecord|undefined>{const r=await this.db.pool.query('SELECT * FROM transaction_receipts WHERE principal_id=$1 AND commit_attempt_id=$2',[principalId,attemptId]);const x=r.rows[0] as Record<string,unknown>|undefined;return x?{id:x['id'] as string,commitAttemptId:x['commit_attempt_id'] as string,principalId:x['principal_id'] as string,providerReference:x['provider_reference'] as string|undefined,status:x['status'] as string,receipt:x['receipt'],createdAt:x['created_at'] as Date}:undefined;}
 async createReconciliation(v:ReconciliationAttemptRecord):Promise<void>{await this.db.pool.query('INSERT INTO reconciliation_attempts(id,commit_attempt_id,principal_id,status,result,completed_at) VALUES($1,$2,$3,$4,$5,$6)',[v.id,v.commitAttemptId,v.principalId,v.status,v.result,v.completedAt]);}
 async getReconciliation(principalId:string,id:string):Promise<ReconciliationAttemptRecord|undefined>{const r=await this.db.pool.query('SELECT * FROM reconciliation_attempts WHERE principal_id=$1 AND id=$2',[principalId,id]);const x=r.rows[0] as Record<string,unknown>|undefined;return x?{id:x['id'] as string,commitAttemptId:x['commit_attempt_id'] as string,principalId:x['principal_id'] as string,status:x['status'] as string,result:x['result'],createdAt:x['created_at'] as Date,completedAt:x['completed_at'] as Date|undefined}:undefined;}
 async completeReconciliation(principalId:string,id:string,status:string,result:unknown):Promise<boolean>{const r=await this.db.pool.query(`UPDATE reconciliation_attempts SET status=$3,result=$4,completed_at=now() WHERE principal_id=$1 AND id=$2 AND completed_at IS NULL RETURNING id`,[principalId,id,status,result]);return r.rowCount===1;}
}
