import type {
  CapabilityDescriptorV2,
  PhoneCapabilityV2,
} from './types';

const descriptor = (
  value: CapabilityDescriptorV2,
): CapabilityDescriptorV2 => Object.freeze(value);

export const capabilityCatalogV2: Readonly<
  Record<PhoneCapabilityV2, CapabilityDescriptorV2>
> = Object.freeze({
  activate: descriptor({
    capability: 'activate',
    effect: 'navigation',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: true,
  }),
  add_cart_item: descriptor({
    capability: 'add_cart_item',
    effect: 'reversible_external',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  ask_user: descriptor({
    capability: 'ask_user',
    effect: 'read_only',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  back: descriptor({
    capability: 'back',
    effect: 'navigation',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  cancel_task: descriptor({
    capability: 'cancel_task',
    effect: 'read_only',
    idempotency: 'operation_key',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  clear_text: descriptor({
    capability: 'clear_text',
    effect: 'local_edit',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: true,
  }),
  confirm_order: descriptor({
    capability: 'confirm_order',
    effect: 'irreversible',
    idempotency: 'at_most_once',
    requiresConfirmation: true,
    requiresFreshObservation: false,
  }),
  home: descriptor({
    capability: 'home',
    effect: 'navigation',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  inspect_cart: descriptor({
    capability: 'inspect_cart',
    effect: 'read_only',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  launch_app: descriptor({
    capability: 'launch_app',
    effect: 'navigation',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  observe: descriptor({
    capability: 'observe',
    effect: 'read_only',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  patch_plan: descriptor({
    capability: 'patch_plan',
    effect: 'read_only',
    idempotency: 'operation_key',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  prepare_checkout: descriptor({
    capability: 'prepare_checkout',
    effect: 'financial',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  reconcile_operation: descriptor({
    capability: 'reconcile_operation',
    effect: 'read_only',
    idempotency: 'operation_key',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  remove_cart_item: descriptor({
    capability: 'remove_cart_item',
    effect: 'reversible_external',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  scroll: descriptor({
    capability: 'scroll',
    effect: 'navigation',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: true,
  }),
  search_products: descriptor({
    capability: 'search_products',
    effect: 'read_only',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  select_payment_method: descriptor({
    capability: 'select_payment_method',
    effect: 'financial',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: true,
  }),
  select_product: descriptor({
    capability: 'select_product',
    effect: 'read_only',
    idempotency: 'operation_key',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  set_cart_item_quantity: descriptor({
    capability: 'set_cart_item_quantity',
    effect: 'reversible_external',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
  set_text: descriptor({
    capability: 'set_text',
    effect: 'local_edit',
    idempotency: 'desired_state',
    requiresConfirmation: false,
    requiresFreshObservation: true,
  }),
  submit: descriptor({
    capability: 'submit',
    effect: 'external_side_effect',
    idempotency: 'at_most_once',
    requiresConfirmation: true,
    requiresFreshObservation: true,
  }),
  wait_for_change: descriptor({
    capability: 'wait_for_change',
    effect: 'read_only',
    idempotency: 'none',
    requiresConfirmation: false,
    requiresFreshObservation: false,
  }),
});
