import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { ApprovalService, ApprovalStateError, type ApprovalRepository, type ApprovalRequestRecord, type ApprovalBinding } from '../src/approvals/approval-service.js';

const hash = 'a'.repeat(64);
const binding: ApprovalBinding = { principalId: 'alice', proposalId: 'proposal-1', proposalRevision: 1, proposalHash: hash };
class MemoryRepository implements ApprovalRepository {
  public requests = new Map<string, ApprovalRequestRecord>();
  public invalidatedCapabilities: ApprovalBinding[] = [];
  public async create(record: ApprovalRequestRecord): Promise<void> { this.requests.set(record.id, structuredClone(record)); }
  public async get(principalId: string, id: string): Promise<ApprovalRequestRecord | undefined> { const value=this.requests.get(id); return value?.principalId===principalId ? structuredClone(value) : undefined; }
  public async transitionPending(binding: ApprovalBinding, id: string, status: 'approved'|'rejected'|'expired', at: Date): Promise<ApprovalRequestRecord | undefined> { const value=this.requests.get(id); if (!value || value.status!=='pending' || !same(value,binding)) return undefined; const changed={...value,status,decidedAt:at}; this.requests.set(id,changed); return structuredClone(changed); }
  public async invalidateStale(current: ApprovalBinding, at: Date): Promise<void> { for (const [id,r] of this.requests) if(r.principalId===current.principalId&&r.proposalId===current.proposalId&&!same(r,current)&&r.status==='pending') this.requests.set(id,{...r,status:'expired',decidedAt:at}); this.invalidatedCapabilities.push(current); }
}
const same=(a:ApprovalBinding,b:ApprovalBinding): boolean=>a.principalId===b.principalId&&a.proposalId===b.proposalId&&a.proposalRevision===b.proposalRevision&&a.proposalHash===b.proposalHash;
function setup(): {repo:MemoryRepository;service:ApprovalService;setNow:(x:string)=>void} { let now=new Date('2026-01-01T00:00:00Z'); const repo=new MemoryRepository(); const service=new ApprovalService(repo,()=>now); return {repo,service,setNow:(x:string): void=>{now=new Date(x);}}; }

describe('approval request policy',()=>{
  it('creates a 256-bit portal token but persists only its SHA-256 hash',async()=>{ const {repo,service}=setup(); const made=await service.create({...binding,expiresAt:new Date('2026-01-01T00:05:00Z')}); expect(Buffer.from(made.requestToken,'base64url')).toHaveLength(32); const stored=repo.requests.get(made.request.approvalRequestId)!; expect(stored.requestTokenHash).toBe(createHash('sha256').update(made.requestToken).digest('hex')); expect(JSON.stringify(stored)).not.toContain(made.requestToken); });
  it.each(['approved','rejected'] as const)('moves pending to %s with exact token and binding',async decision=>{ const {service}=setup(); const made=await service.create({...binding,expiresAt:new Date('2026-01-01T00:05:00Z')}); expect((await service.decide({...binding,approvalRequestId:made.request.approvalRequestId,requestToken:made.requestToken,decision})).status).toBe(decision); });
  it('expires deterministically and cannot be decided afterwards',async()=>{ const x=setup(); const made=await x.service.create({...binding,expiresAt:new Date('2026-01-01T00:05:00Z')}); x.setNow('2026-01-01T00:05:00Z'); expect((await x.service.get(binding,made.request.approvalRequestId)).status).toBe('expired'); await expect(x.service.decide({...binding,approvalRequestId:made.request.approvalRequestId,requestToken:made.requestToken,decision:'approved'})).rejects.toBeInstanceOf(ApprovalStateError); });
  it('does not change terminal decisions',async()=>{ const {service}=setup(); const made=await service.create({...binding,expiresAt:new Date('2026-01-01T00:05:00Z')}); await service.decide({...binding,approvalRequestId:made.request.approvalRequestId,requestToken:made.requestToken,decision:'approved'}); await expect(service.decide({...binding,approvalRequestId:made.request.approvalRequestId,requestToken:made.requestToken,decision:'rejected'})).rejects.toBeInstanceOf(ApprovalStateError); });
  it('invalidates old revision requests and authorizations',async()=>{ const {repo,service}=setup(); const old=await service.create({...binding,expiresAt:new Date('2026-01-01T00:05:00Z')}); const revised={...binding,proposalRevision:2,proposalHash:'b'.repeat(64)}; await service.invalidateStale(revised); expect(repo.requests.get(old.request.approvalRequestId)?.status).toBe('expired'); expect(repo.invalidatedCapabilities).toEqual([revised]); });
  it('enforces owner isolation and exact proposal/revision/hash binding',async()=>{ const {service}=setup(); const made=await service.create({...binding,expiresAt:new Date('2026-01-01T00:05:00Z')}); for(const changed of [{...binding,principalId:'bob'},{...binding,proposalId:'other'},{...binding,proposalRevision:2},{...binding,proposalHash:'b'.repeat(64)}]) await expect(service.decide({...changed,approvalRequestId:made.request.approvalRequestId,requestToken:made.requestToken,decision:'approved'})).rejects.toBeInstanceOf(ApprovalStateError); expect((await service.get(binding,made.request.approvalRequestId)).status).toBe('pending'); });
});
