/* eslint-disable @typescript-eslint/explicit-function-return-type */
import { describe,expect,it } from 'vitest';
import { ProviderAuthService,OwnershipError,type ProviderSessionRepository } from '../src/index.js';
import type { ProviderSession } from '@errandos/contracts';
const alice='alice' as ProviderSession['principalId']; const bob='bob' as ProviderSession['principalId']; const provider={kind:'known' as const,value:'blinkit' as const};
class Repo implements ProviderSessionRepository { m=new Map<string,ProviderSession>(); async get(id:string){return this.m.get(id)} async find(p:ProviderSession['principalId'],v:ProviderSession['provider'],a:string){return [...this.m.values()].find(s=>s.principalId===p&&s.provider.value===v.value&&s.accountKey===a)} async save(s:ProviderSession){this.m.set(s.id,s)} }
const setup=(now=new Date('2026-01-01T00:00:00Z'))=>{const repo=new Repo(); const service=new ProviderAuthService(repo,{create:async()=> 'opaque-profile'},{begin:async({sessionId})=>({supervisedLoginUrl:`https://login.errandos.test/${sessionId}`,tokenReference:'token-ref'})},()=>now); return {repo,service};};
describe('provider auth lifecycle',()=>{
 it('transitions without exposing secrets and redacts status',async()=>{const {service}=setup(); expect((await service.getAuthStatus(alice,provider,'main')).status).toBe('missing'); const begun=await service.beginSupervisedLogin(alice,provider,'main','oauth'); expect(begun).toMatchObject({status:'authenticating',tokenReference:'token-ref'}); expect(JSON.stringify(begun)).not.toMatch(/cookie|password|otp/i); await service.reportChallenge(alice,begun.sessionId,'otp'); expect((await service.getAuthStatus(alice,provider,'main')).status).toBe('challenge_required'); await service.completeLogin(alice,begun.sessionId,'2026-02-01T00:00:00.000Z',{label:'A•••'}); expect(await service.getAuthStatus(alice,provider,'main')).toMatchObject({status:'active',accountDisplay:{label:'A•••'}}); await service.revokeSession(alice,begun.sessionId); expect((await service.getAuthStatus(alice,provider,'main')).status).toBe('revoked');});
 it('enforces ownership',async()=>{const {service}=setup(); const s=await service.beginSupervisedLogin(alice,provider,'main','oauth'); await expect(service.completeLogin(bob,s.sessionId)).rejects.toBeInstanceOf(OwnershipError); expect((await service.getAuthStatus(bob,provider,'main')).status).toBe('missing');});
 it('deterministically expires active sessions',async()=>{const {service}=setup(new Date('2026-03-01T00:00:00Z')); const s=await service.beginSupervisedLogin(alice,provider,'main','oauth'); await service.completeLogin(alice,s.sessionId,'2026-02-01T00:00:00.000Z'); expect((await service.getAuthStatus(alice,provider,'main')).status).toBe('expired');});
});
